### ISSUE TITLE
Error in local setup

### ISSUE THREAD

**Issue by plushpluto** [pqaidevteam/pqai#53]
Dear PQAI,

This is a wonderful effort. I am trying to setup a local env for myself. I have followed your steps. But, I am not able to render anything except docs. Please help.

I have a local ubuntu 20.04. No GPU. And I have followed exactly the steps from https://github.com/pqaidevteam/pqai/wiki/Deployment. 

This is what I get on the console.
/pqai/pqai-env/lib/python3.8/site-packages/huggingface_hub/snapshot_download.py:6: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.
  warnings.warn(
INFO:waitress:Serving on http://0.0.0.0:8501

But when I do http://0.0.0.0:8501/patents/US7654321B2, I get "Server error". Please help

Thanks,
Badri

**Comment by mahesh-maan** [comment]
Hi @plushpluto Thanks for reaching out.

When you get "Server error" - do you also see an error message on the terminal? If yes, can you post it here?

Also, have you set up the environment variables in a .env file? Usually it's an improperly set variable that causes problems in a first set up.

**Comment by mahesh-maan** [comment]
@plushpluto Try setting these and see if it resolves the issue?

```
SMART_INDEX_SELECTION=0
USE_RERANKER=0
DEFAULT_SBERT_MODEL="pqai-vectorizer-v3"
```

**Comment by mahesh-maan** [comment]
@plushpluto Is there is any API route that is working for you? Or you are getting the same error on all the routes?

**Comment by mahesh-maan** [comment]
@plushpluto Can you add a line in that code to print the exception that is getting raised? Hopefully that should give a lead.

**Comment by mahesh-maan** [comment]
@plushpluto Sorry I was travelling today so I couldn't reply sooner. Could you try printing the exception using `traceback.print_exc()`?

You'd have to `import traceback`, thereafter replace the `print("Server Exception:", e)` line with `traceback.print_exc()` so we'll get to know exactly where the error occurs.

**Comment by mahesh-maan** [comment]
@plushpluto On the `/patents/:pn` route this error is expected since you have not configured the S3 bucket in the test setup. Could you please also share the error you are getting on the search route(`/search/102`)?

For that you can make the following request: `http://localhost:8501/search/102?q=system&type=patent&n=10`

**Comment by mahesh-maan** [comment]
@plushpluto Could you please try setting `DEFAULT_SBERT_MODEL=vectorizer_distilbert_poc` in `.env` file, then restarting the server and again hitting the search route?

Looks like the test index is built using an older version of the vectorizer that had a different vector length.

**Comment by mahesh-maan** [comment]
Hi @plushpluto did you try the above?

**Comment by mahesh-maan** [comment]
@plushpluto Checking this. It seems to be a Python environment issue. It would help if you could share the output of `pip freeze` for diagnosis.

**Comment by mahesh-maan** [comment]
@plushpluto trying to reproduce your error.

**Comment by mahesh-maan** [comment]
Hi @plushpluto sorry for the delay.

I was able to reproduce and pin-point the issue you are facing.

The problem was not due to something wrong on your side. It was a miss from my end. When I had rolled out an update the vectorizer last time, I did not update the sample index. That's why first you were facing a vector dimension mismatch and later the environment issue (when you tried to use the old vectorizer).

Anyway, here are the steps you need to take to get it working (I just verified correct working on a fresh system):

1. Empty the `indexes` directory (to remove the old index)
2. Download the new sample index: https://s3.amazonaws.com/pqai.s3/public/sample-index.zip to any folder on your system (it's the same link as given in the deployment instructions; I have just replaced the file behind it)
3. Extract the contents of the downloaded zip file (again, a `.faiss` file and a `.json` file) into the `indexes` directory - after this step, this directory should have a `2000.faiss` file and a `2000.items.json` file.
4. Clear the .env file and put the following values in it (copy-paste the whole thing)

```
PQAI_S3_BUCKET_NAME=             
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
API_PORT=8501
MONGO_PORT=27017
MONGO_HOST="localhost"
MONGO_USER=
MONGO_PASSWORD=
MONGO_DBNAME="pqai"
MONGO_PAT_COLL="bibliography"
MONGO_NPL_COLL="npl"
SMART_INDEX_SELECTION=0
DEFAULT_SBERT_MODEL="pqai-vectorizer-v3"
USE_RERANKER=0
DISABLE_GPU=1
SENTRY_URL=
OUTGOING_EXT=0
INCOMING_EXT=0
USE_FAISS_INDEXES=1
USE_ANNOY_INDEXES=0
TOKEN_AUTHENTICATION=0
```
5. Run the server with `python server.py`
6. Test with this URL: http://localhost:8501/search/102/?q=fire%20fighting%20drones&lq=&type=patent&n=10

Let me know how it goes.

**Comment by mahesh-maan** [comment]
@plushpluto Hope the routes are working for you. If yes, could you please mark this issue as resolved?

(routes requiring S3 data access might not work - for that I'll add a feature on the roadmap to pull data from main PQAI server)
